services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5454:5454
    networks:
      - default

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000   # API
      - 9001:9001   # Console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    command: server /data --console-address ":9001"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  minio_data: